// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMFdcXPhoveIcJUiY5ev6pvJRHTt_I7s',
    appId: '1:11998369301:web:36950fd473e65b0c5ee01c',
    messagingSenderId: '11998369301',
    projectId: 'flutter-914c9',
    authDomain: 'flutter-914c9.firebaseapp.com',
    databaseURL: 'https://flutter-914c9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-914c9.appspot.com',
    measurementId: 'G-FQ7FG3KK5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDAsSmimvZ0cOEL1UBsVBbdHwjbfxf0g',
    appId: '1:11998369301:android:43aa94e2b36d5f1d5ee01c',
    messagingSenderId: '11998369301',
    projectId: 'flutter-914c9',
    databaseURL: 'https://flutter-914c9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-914c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgFcxVepdqbZlkBVdfusFDJNo21dmRLZA',
    appId: '1:11998369301:ios:e3f9ee1bfe538bb45ee01c',
    messagingSenderId: '11998369301',
    projectId: 'flutter-914c9',
    databaseURL: 'https://flutter-914c9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-914c9.appspot.com',
    iosClientId: '11998369301-arr9v6h35enpk2md53h3p5p1cf49o44u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgFcxVepdqbZlkBVdfusFDJNo21dmRLZA',
    appId: '1:11998369301:ios:e3f9ee1bfe538bb45ee01c',
    messagingSenderId: '11998369301',
    projectId: 'flutter-914c9',
    databaseURL: 'https://flutter-914c9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-914c9.appspot.com',
    iosClientId: '11998369301-arr9v6h35enpk2md53h3p5p1cf49o44u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
